export enum PermissionsValues {
  READ_FEATURE_FLAGS = 'READ_FEATURE_FLAGS',
  CREATE_FEATURE_FLAGS = 'CREATE_FEATURE_FLAGS',
  UPDATE_FEATURE_FLAGS = 'UPDATE_FEATURE_FLAGS',
  REMOVE_FEATURE_FLAGS = 'INTERNAL_ADMIN_REMOVE_FEATURE_FLAGS',

  READ_SUBSCRIPTION_PLAN = 'READ_SUBSCRIPTION_PLAN',
  CREATE_SUBSCRIPTION_PLAN = 'ADMIN_CREATE_SUBSCRIPTION_PLAN',
  UPDATE_SUBSCRIPTION_PLAN = 'ADMIN_UPDATE_SUBSCRIPTION_PLAN',
  REMOVE_SUBSCRIPTION_PLAN = 'INTERNAL_ADMIN_REMOVE_SUBSCRIPTION_PLAN',
}
