export enum PermissionsValues {
  READ_FEATURE_FLAGS = 'READ_FEATURE_FLAGS',
  CREATE_FEATURE_FLAGS = 'CREATE_FEATURE_FLAGS',
  UPDATE_FEATURE_FLAGS = 'UPDATE_FEATURE_FLAGS',
  REMOVE_FEATURE_FLAGS = 'INTERNAL_ADMIN_REMOVE_FEATURE_FLAGS',
}
